# Generated by Django 6.0.1 on 2026-02-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_sesionactiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactiva',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
