# Generated by Django 6.0.1 on 2026-02-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_sesionactiva_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionactiva',
            name='fecha',
        ),
    ]
