# Generated by Django 6.0.1 on 2026-02-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_remove_sesionactiva_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SesionActiva',
        ),
    ]
