services:
  db:
    image: postgres:15
    container_name: ganadero_db
    environment:
      POSTGRES_DB: ganadero_db
      POSTGRES_USER: ganadero_user
      POSTGRES_PASSWORD: ganadero_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ganadero_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ganadero_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ganadero.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ganadero_network

volumes:
  postgres_data:

networks:
  ganadero_network:
    driver: bridge
